### ISSUE TITLE
How to generate JSON schema files with examples

### ISSUE THREAD

**Issue by Kindrat** [mulesoft/raml-for-jax-rs#42] opened 2015-02-27 18:33 UTC
As I see,  private void visit(IMethodModel m, String path) in ResourceVisitor generates only xml schema files. But addMethod (378:384) contains logic to add JSON schema name.

How should I add JSON bodies correctly from maven plugin?

**Comment by petrochenko-pavel-a** [comment] 2015-03-02 17:22
Hi Kindrat,
Thank you for reporting it seems to be a regression in Maven plogin for raml->jaxrs. I will try to fix it asap.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment] 2015-03-02 17:26
Please let me know if same did not works for you in eclipse plugin or in command line.
Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment] 2015-03-03 20:57
Hi I just pushed fix for the issue , please let me know if you still have any problems with JSON schemas.

**Comment by petrochenko-pavel-a** [comment] 2015-03-06 08:00
Please let me know if  you still have any problems (closing for now)

**Comment by Kindrat** [comment] 2015-03-06 13:46
I'm able to generate json stuff, but schema is using Class name, and include string - name.toLowerCase which breaks load.

**Comment by petrochenko-pavel-a** [comment] 2015-03-06 16:19
>I'm able to generate json stuff, but schema is using Class name, and include string - name.toLowerCase >which breaks load.

It sounds a bit confusing.  From what I am seeing schema name is based on class name to lowercase and include string is also based on same naming convention.

May you please provide a sample which breaks load.

Thanks in advance,
Pavel

**Comment by Kindrat** [comment] 2015-03-06 18:09
https://dl.dropboxusercontent.com/u/7532224/RamlDemo.zip
Dto is saved as "examples/Profile.json", raml contains "example: !include examples/profile.json"

**Comment by petrochenko-pavel-a** [comment] 2015-03-07 18:32
you are totally right all should be lowercased now

**Closed** 2015-03-07 19:55 UTC

**Comment by Kindrat** [comment] 2015-03-12 19:35
Yet another posiible bug in json schema creation. Each dto is wrapped in empty object, using this dto as inner field.
Generated value:
```
{
  "profile" : {
    "id" : "some long value" ,
    "profilekey" : "some string value" ,
    "profilename" : "some string value"
  }
}
```
Proper value:
```
{
    "id" : "some long value" ,
    "profilekey" : "some string value" ,
    "profilename" : "some string value"
}
```

**Comment by Kindrat** [comment] 2015-03-12 20:32
Please, tale a look at this patch:
https://dl.dropboxusercontent.com/u/7532224/RootElementInJsonSchema.patch

**Comment by ddossot** [comment] 2015-03-12 20:38
@Kindrat this has been closed, I think you'd rather open a new one so this empty root object problem can be tackled separately.

Also, pull requests are the way to propose fixes, not patch files. Pull requests are easy to visualize in context (thanks to the nice visual diff from GitHub).

**Comment by petrochenko-pavel-a** [comment] 2015-03-12 21:06
Thanks a lot for finding this. (just fixed it also). You should have it in latest snapshots now.

Regards,
Pavel
