### ISSUE TITLE
NullPointerException at com.mulesoft.jaxrs.raml.annotation.model.FileUtil.fileToString(FileUtil.java:25)

### ISSUE THREAD

**Issue by dkirrane** [mulesoft/raml-for-jax-rs#98] opened 2015-06-04 10:56 UTC
I'm hitting the following NPE running `jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml`

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.399s
[INFO] Finished at: Thu Jun 04 11:52:40 BST 2015
[INFO] Final Memory: 32M/302M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml (raml) on project wa-im-rest-war: Execution raml of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml (raml) on project wa-im-rest-war: Execution raml of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution raml of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.util.Scanner.<init>(Scanner.java:656)
        at com.mulesoft.jaxrs.raml.annotation.model.FileUtil.fileToString(FileUtil.java:25)
        at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.generateXSDForClass(ResourceVisitor.java:869)
        at com.mulesoft.jaxrs.raml.annotation.model.reflection.RuntimeResourceVisitor.generateXMLSchema(RuntimeResourceVisitor.java:100)
        at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.processResponses(ResourceVisitor.java:543)
        at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.addMethod(ResourceVisitor.java:435)
        at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:351)
        at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:229)
        at org.raml.jaxrs.codegen.maven.JaxrsRamlCodegenMojo.execute(JaxrsRamlCodegenMojo.java:156)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by dkirrane** [comment] 2015-06-04 12:48
I think this may be related to adding `response` & `responseContainer` to my Swagger Annotations
Example: 
```
    @ApiOperation(value = "Creates Something", response = Response.class)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successfully created Something", response = String.class),
        @ApiResponse(code = 400, message = "Invalid request", response = String.class, responseContainer = "Map[String, String]"),
        @ApiResponse(code = 409, message = "Agent already exists", response = MyAppError.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = MyAppError.class)
    })
    public Response create(@ApiParam(value = "The Something that needs to be added", required = true) Something entity) {
           ....
    }

Using latest Swagger annotations from version
```
            <dependency>
                <groupId>com.wordnik</groupId>
                <artifactId>swagger-jaxrs</artifactId>
                <version>1.5.2-M2</version>
                <scope>compile</scope>
            </dependency>    
```
```

**Comment by KonstantinSviridov** [comment] 2015-06-05 00:45
Hi @dkirrane 

The NPE is thrown because JAXB schema generator fails to process response class which is String. I've pushed the fix, so you will stop getting NPE.

Schemes and examples, however, are not generated or generated incorrectly because the 'resourceContainer' attribute is not supported and we do not process non JAXB types.

By the way, could you please provide me documentation you follow when using the `@ApiOperation`.

According to [what I know](http://docs.swagger.io/swagger-core/apidocs/com/wordnik/swagger/annotations/ApiOperation.html#responseContainer()), the only available values of `responseContainer` are `Array`, `List` and `Set`. Moreover, as a value of `response` I would expect a JAXB class. Otherwise, how would you serialize it to XML?

Regards, Konstantin.

**Comment by dkirrane** [comment] 2015-06-05 10:05
Thanks, raml file and schemas generate now. However, I'm hitting another issue with `response`.

`@ApiResponse(code = 200, message = "Some message", response = Void.class)`

Also, it looks like even if I omit`response` from the `@ApiResponse` annotation then it will default to using `java.lang.Void` anyway. Hence I hit the same issue.

RAML console complains with:
```
cannot fetch http://ip:9080/examples/raml/examples/void.json (Not Found)
```

RE: expecting a JAXB class
Our REST API uses JSON only. If that's what you mean. So we don't have any JAXB annotations on our request/response POJOs. AppServer/Jackson can marshall/unmarshall these POJOs withour requireing JAXB

**Comment by dkirrane** [comment] 2015-06-05 10:46
Actually only the raml file and XSD schemas are getting generated.
All the example json files are missing: `!include examples/response.json`

**Comment by KonstantinSviridov** [comment] 2015-06-08 09:12
Ok, I have enabled support for generating xml and json examples and json schemes for non JAXB types. For generating XSDs we use a JAXB generator, and it skips those properties which have non JAXB types.

If there is something else you need (apart from resourceContainer ), please, let us know.

Regards, Konstantin.

**Comment by dkirrane** [comment] 2015-06-08 10:21
Getting this I guess for response = String.class
`schemas/string-jsonschema.json (Not Found)`

**Comment by KonstantinSviridov** [comment] 2015-06-08 21:10
Thanks again for reporting the problem.
Fixed in 1.3.4-SNAPSHOT

**Comment by dkirrane** [comment] 2015-06-09 10:50
Not sure whats causing this.

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.mulesoft.jaxrs.raml.annotation.model.reflection.ReflectionField.getJAXBType(ReflectionField.java:66)
	at com.mulesoft.jaxrs.raml.jaxb.JAXBElementProperty.getJAXBType(JAXBElementProperty.java:47)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.writeProperty(SchemaModelBuilder.java:69)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.generateType(SchemaModelBuilder.java:49)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.writeProperty(SchemaModelBuilder.java:71)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.generateType(SchemaModelBuilder.java:49)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.writeProperty(SchemaModelBuilder.java:71)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.generateType(SchemaModelBuilder.java:49)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.writeProperty(SchemaModelBuilder.java:71)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.generateType(SchemaModelBuilder.java:49)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.writeProperty(SchemaModelBuilder.java:71)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.generateType(SchemaModelBuilder.java:49)
	at com.mulesoft.jaxrs.raml.jaxb.SchemaModelBuilder.buildSchemaModel(SchemaModelBuilder.java:24)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.afterSchemaGen(ResourceVisitor.java:1060)
	at com.mulesoft.jaxrs.raml.annotation.model.reflection.RuntimeResourceVisitor.generateXMLSchema(RuntimeResourceVisitor.java:94)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.processResponses(ResourceVisitor.java:588)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.addMethod(ResourceVisitor.java:444)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:360)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:235)
	at org.raml.jaxrs.codegen.maven.JaxrsRamlCodegenMojo.execute(JaxrsRamlCodegenMojo.java:156)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

**Comment by KonstantinSviridov** [comment] 2015-06-09 15:24
I have reproduced your problem. It occurs when the class specified in the `response` attribute has a type parameter say `T` and some property of type `T`. The sad thing is that if you set the same class as return type, with all parameters specified, you also get an exeption (but it's not the same as yours). So, I'm starting to work on it.

**Comment by dkirrane** [comment] 2015-06-09 17:13
I narrowed down my issue to the `@ApiOperation(value = "Description", response = Response.class)`
I removed `response = Response.class` from above the the issue went away. I guess it's redundant anway if you have specified `@ApiResponses`

**Comment by dkirrane** [comment] 2015-06-09 17:27
I think this is the last issue I'm hitting.
`UserResponse ` POJO contains: 
`private Map<Integer, AddressResponse> addressResponseMap;`

`AddressResponse` POJO contains:
`private List<Map<String,String>> addressList;``

And 

```
--- jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml (raml) @ my-war ---
com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
java.util.Map is an interface, and JAXB can't handle interfaces.
	this problem is related to the following location:
		at java.util.Map
		at public java.util.List com.mycompany.model.AddressResponse.getAddressList()
		at com.mycompany.model.AddressResponse
		at public java.util.Map com.mycompany.model.UserResponse.getAddressResponseMap()
		at com.mycompany.model.UserResponse
java.util.Map does not have a no-arg default constructor.
	this problem is related to the following location:
		at java.util.Map
		at public java.util.List com.mycompany.model.AddressResponse.getAddressList()
		at com.mycompany.model.AddressResponse
		at public java.util.Map com.mycompany.model.UserResponse.getAddressResponseMap()
		at com.mycompany.model.UserResponse

	at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:102)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:438)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:286)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:139)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:248)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:235)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:432)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:637)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.generateXSDForClass(ResourceVisitor.java:874)
	at com.mulesoft.jaxrs.raml.annotation.model.reflection.RuntimeResourceVisitor.generateXMLSchema(RuntimeResourceVisitor.java:81)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.processResponses(ResourceVisitor.java:553)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.addMethod(ResourceVisitor.java:444)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:360)
	at com.mulesoft.jaxrs.raml.annotation.model.ResourceVisitor.visit(ResourceVisitor.java:235)
	at org.raml.jaxrs.codegen.maven.JaxrsRamlCodegenMojo.execute(JaxrsRamlCodegenMojo.java:156)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

**Comment by KonstantinSviridov** [comment] 2015-06-11 03:04
Ok, fixed the type parameters issue for Maven and Eclipse plugins. Tomorrow I'll check if there is something to be done with console plugin.

As JAXB generator does not process parameter types (it sets `xs:anyType` as type), we feel comfortable to act the same way when generatin examples and JSON schemes. It would be nice to implement our own XSD generator, but this task is far from being of high priority. 

As for your last issue, it is a known problem that JAXB does not support interfaces from box (in your example Map is an interface). For example, see (https://weblogs.java.net/blog/kohsuke/archive/2006/06/jaxb_and_interf.html)[here] and (https://jaxb.java.net/guide/Mapping_interfaces.html)[here]. So, for now we will not generate XSDs for such cases. But we should, probably, generate examples and JSON schemas.

**Comment by KonstantinSviridov** [comment] 2015-06-11 03:19
I've also visited a Swagger Google group and asked some questions about `responseContainer`.

So, possible values are `List`, `Set` and `Map`, and it is not allowed to use value like `Map[String,String]` (see [here](https://groups.google.com/forum/#!topic/swagger-swaggersocket/vGWn7PGI85U)).

Another question is what is the name of root element of XSD generated. The answer is udefined ([here](https://groups.google.com/forum/#!topic/swagger-swaggersocket/QpwiDHT1qCU)). So, we have two choices: not to generate XSD and XML in such cases at all ot to give these elements somedefault names. I think, at first approach we will select the first option.

Regards, Konstantiin.

**Comment by dkirrane** [comment] 2015-06-11 10:41
Thanks, I just ran `jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml` again this morning.
Not sure if the fix was pushed cause I'm still getting the following in the generated RAML file:

```
          body: 
            application/json: 
              schema: string-jsonschema
              example: !include examples/string.json
```

raml console error `raml/examples/string.json (Not Found)`

**Comment by KonstantinSviridov** [comment] 2015-06-11 20:42
I can not reproduce your problem now.
I've just checked out 1.3.4-SNAPSHOT from here, installed it to my local repository and tested it.

If you still see it, please, provide a small example.

**Comment by KonstantinSviridov** [comment] 2015-06-12 02:32
Now JAXB generator failures do not affect JSON schemes and examples generation.

It appears, that JAXB generator understands java.util.Map and some classes that implement it (though it does not understand List<Map>). We will also implement Map support.

**Comment by KonstantinSviridov** [comment] 2015-06-15 12:16
Ok.

1. Maps support is implemented (for JSON we expect only String as key class).

2. `responseContainer` support is implemented for JSON. `List`, `Set` and `Map` are supported.

**Closed** 2015-06-16 17:36 UTC
