### ISSUE TITLE
Upload Maven Snapshots and Releases to OSS Sonatype

### ISSUE THREAD

**Issue by dkirrane** [mulesoft/raml-for-jax-rs#34] opened 2015-02-09 10:17 UTC
Any plans to upload Snapshots and Releases to https://oss.sonatype.org or Maven Central

http://central.sonatype.org/pages/ossrh-guide.html

**Comment by ddossot** [comment] 2015-02-09 17:26
Duplicate of issue #23 ... still no move from MuleSoft to make this happen :sob:

**Comment by petrochenko-pavel-a** [comment] 2015-02-09 18:09
Hi guys, trying to resolve it right now.

**Comment by talios** [comment] 2015-02-15 10:52
Any progress?

**Comment by petrochenko-pavel-a** [comment] 2015-02-15 11:00
Hi Talios we established publishing to https://repository-master.mulesoft.org/
please let me know if it is not enough for your needs.


Regards,
Pavel

**Comment by ddossot** [comment] 2015-02-15 17:11
I think this is your internal repo, the public one I think is: https://repository.mulesoft.org/nexus/content/repositories/public

And indeed I can find the RAML codegen stuff here: https://repository.mulesoft.org/nexus/content/repositories/public/org/raml/ :+1: 

(of course, the next issue will be about _when can get a release_ the version of these plugins is 1.3.2 but there's no release nowhere...)

**Comment by petrochenko-pavel-a** [comment] 2015-02-16 11:35
Hm, actually I can  : 
see: https://repository.mulesoft.org/nexus/content/repositories/public/org/raml/raml-jaxrs-codegen-core/

Regards,
Pavel

**Comment by ddossot** [comment] 2015-02-16 16:38
This is the exact same link I gave, not sure what you mean then.

**Comment by talios** [comment] 2015-02-19 03:32
Updated my local branches and working like a charm - added the mulesoft repo to $work's nexus.  Cheers all!

**Comment by petrochenko-pavel-a** [comment] 2015-02-19 18:15
We discussed it internally and decided to publish it to Sonatype too, so reopening.

Regards,
Pavel

**Comment by ddossot** [comment] 2015-02-19 18:26
Oooohhh that's cool :dancers:

**Comment by hindsholm** [comment] 2015-02-20 10:35
The repository at https://repository.mulesoft.org/nexus/content/repositories/public/org/raml/raml-jaxrs-codegen-core/ is definitely a step in the right direction, and the Sonatype publish is even better!

BUT unfortunately the repository does not contain jaxrs-raml-maven-plugin. The "opposite one" (raml-jaxrs-maven-plugin) is there, so please add jaxrs-raml-maven-plugin as well!

**Comment by petrochenko-pavel-a** [comment] 2015-02-20 14:23
It is because it has another group it : com.mulesoft.jaxrs-raml

I am filing issue to make all projects using same group id.

Regards,
Pavel

**Comment by hindsholm** [comment] 2015-02-23 08:31
Actually the group id is the same for both plugins. If you take a look at [the jaxrs-raml-maven-plugin pom](https://github.com/mulesoft/raml-for-jax-rs/blob/master/jaxrs-to-raml/jaxrs-raml-maven-plugin/pom.xml), you will see that the group id is `org.raml.plugins` just as it is for [raml-jaxrs-maven-plugin](https://github.com/mulesoft/raml-for-jax-rs/blob/master/raml-to-jaxrs/maven-plugin/pom.xml).

**Comment by ddossot** [comment] 2015-02-23 14:49
@hindsholm Did you try adding the repo to your POM? Indeed the repos below https://repository.mulesoft.org/nexus/content/repositories/ are mirrors: artifacts "appear" there when they get pulled by Maven so that could be why you don't see `jaxrs-raml-maven-plugin` there: until someone pulls it, it won't show.

**Comment by hindsholm** [comment] 2015-02-23 15:25
I didn't think of that, but I will try it. Thanx.

**Comment by hindsholm** [comment] 2015-02-24 12:13
Unfortunately I can't make it work. jaxrs-raml-maven-plugin is apparently not available in https://repository.mulesoft.org/nexus/content/repositories/.

**Comment by ddossot** [comment] 2015-02-24 14:47
@hindsholm :disappointed: It's unfortunately not the only thing that is borked about this release, see: https://github.com/mulesoft/raml-for-jax-rs/issues/40

**Comment by petrochenko-pavel-a** [comment] 2015-02-24 17:01
Hm but botha are available at https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/raml/plugins/

**Comment by ddossot** [comment] 2015-02-24 17:13
But why are they partially available here as well: https://repository.mulesoft.org/nexus/content/repositories/public/org/raml/ ? What's going on with these repos?

**Comment by petrochenko-pavel-a** [comment] 2015-02-24 17:26
Asking people here why it might happen.

**Comment by petrochenko-pavel-a** [comment] 2015-02-24 17:55
https://issues.sonatype.org/browse/OSSRH-14035 filed.

**Comment by talios** [comment] 2015-02-26 22:11
Oh man - I just tried building my branch using the "released" version of the plugin in a sandbox:

  [ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.2:generate (default) on project smx3.agreement:
    Execution default of goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.2:generate failed:
    Plugin org.raml.plugins:raml-jaxrs-maven-plugin:1.3.2 or one of its dependencies could not be resolved:
     Could not find artifact org.raml:raml-parser:jar:0.9-SNAPSHOT in Nexus (http://nexus.smxemail.com/nexus/content/groups/public/) -> [Help 1]
  [ERROR]

WUT? The "released" version of this plugin depends on a `-SNAPSHOT` of the parser? First I saw this release was made without tagging the source, now this?

**Comment by ddossot** [comment] 2015-02-26 22:39
Oh noes :crying_cat_face: Clearly this has not been released with Maven because it would have complained about the dependency on a SNAPSHOT. This calls for a proper `1.3.3` release IMO.

**Comment by petrochenko-pavel-a** [comment] 2015-02-26 22:43
yep. You are right. I am very sorry about snapshot version. Unfortunately I
can not release it with maven because maven release did not updates PDE
artefacts, so I have to update versions with home grown script. I will
update it right now.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment] 2015-02-27 16:25
Hi guys, I published snapshot to sonatype if everything is ok I will publish 1.3.3 tomorrow.

Regards,
Pavel

**Comment by talios** [comment] 2015-03-01 22:52
Was 1.3.3 released at all, doesn't appear to be in central at least?  Was extremely busy over the weekend so didn't manage to check up on this.

**Comment by petrochenko-pavel-a** [comment] 2015-03-02 13:55
only deployed snapshot version to the moment, will do release today

**Comment by ddossot** [comment] 2015-03-11 23:39
Any progress on this? I have a bunch of projects waiting for the release to hit central...

**Comment by Kindrat** [comment] 2015-03-12 14:45
The same. Even snapshot version, fixing #42 , will be enough.

**Comment by petrochenko-pavel-a** [comment] 2015-03-12 21:10
Snapshot with #42 is there. I am waiting for   https://github.com/raml-org/raml-java-parser/pull/58,
(hopefully it will be integrated today). And on my side I need to figure out what happens in https://github.com/mulesoft/raml-for-jax-rs/issues/48. (probably in next 20 minutes)

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment] 2015-03-17 20:22
1.3.3 release is published to central

**Closed by petrochenko-pavel-a** 2015-03-17 20:22 UTC

**Comment by ddossot** [comment] 2015-03-17 23:26
:dancers:  yeehaa! :clap:

**Comment by talios** [comment] 2015-03-18 03:20
w00t! congrats.

**Comment by northlander** [comment] 2015-03-19 11:53
Awesome!
